### PR TITLE
No package declaration in dune-project file

### LINKED ISSUE #882: EXPERIMENTAL: (lint-opam) (failure: No *.opam files found!)
In all the CIs I suddenly receive the following issue:

```
/src: (run (shell "opam lint"))
/src/albatross.opam: Passed.
2023-09-27 21:16.01 ---> saved as "1f4bde9a35dd80c8c20c72df76bec14f519d3400d76082acbbe380ac9a96fe7c"


/src: (run (shell "opam exec -- opam-dune-lint"))
opam-dune-lint: internal error, uncaught exception:
                Failure("No *.opam files found!")
```

Maybe `opam-dune-lint` is going crazy, since `opam lint` managed to find an opam file...

### PR DESCRIPTION
**Pull request by moyodiallo**
Fix for #51 and will also fix https://github.com/ocurrent/ocaml-ci/issues/882 after an upgrade.

### CODE REVIEW

File: main.ml [hunk 1]
```diff
@@ -155,11 +155,15 @@ let main force dir =
...
   let packages = Dune_project.packages project in
-  Paths.iter (fun path _ ->
-      (* prevent `dune describe opam-files` crashing when there is a opam file `*.opam`
-         * and its package description is missing in dune-project file. *)
-      if not (Paths.mem path packages) then Sys.remove path)
-    old_opam_files;
+
+  (* some dune project file has no package description
+   * and avoid removing all the opam files *)
+  if not (Paths.is_empty (Dune_project.packages project)) then (
```
Comment (reynir) [inline main.ml]: `Dune_project.packages project` is computed and bound to `packages` just a few lines above :-)
```suggestion
  if not (Paths.is_empty packages) then (
```

File: tests/test_fix_bug.t [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+  $ opam-dune-lint -f
+  test.opam: changes needed:
+    "fmt" {>= "1.0"}                         [from /]
+    "bos" {with-test & >= "1.0"}             [from /]
+    "opam-state" {with-test & >= "1.0"}      [from /]
+  Note: version numbers are just suggestions based on the currently installed version.
+  Wrote "./test.opam"
+
+  $ cat test.opam | sed 's/= [^&)}]*/= */g'
```
Comment (reynir) [inline tests/test_fix_bug.t]:
```suggestion
  $ sed 's/= [^&)}]*/= */g' test.opam
```

File: main.ml [hunk 3]
```diff
@@ -155,11 +155,15 @@ let main force dir =
...
-         * and its package description is missing in dune-project file. *)
-      if not (Paths.mem path packages) then Sys.remove path)
-    old_opam_files;
+
+  (* some dune project file has no package description
+   * and avoid removing all the opam files *)
+  if not (Paths.is_empty packages) then (
+    old_opam_files |> Paths.iter (fun path _ -> if not (Paths.mem path packages) then Sys.remove path)
+    (* prevent `dune describe opam-files` crashing when there is a opam file `*.opam`
+     * that its package description is missing in dune-project file. *)
```
Comment (reynir) [inline main.ml]: I don't understand this comment, but the case in #51 does not result in a crash when running `dune describe opam-files` with dune.3.10.0. Maybe someone knows why the comment is there(?), and maybe it is not true since dune.X.Y.Z?

Comment (moyodiallo) [reply main.ml]: When you have at least one package declaration in dune-project and you have an opam file `*.opam` that is not declared in dune-project, `dune describe opam-files` will fails with error. I need to change the word crashing. 

The error is like:
```
Error: This opam file doesn't have a corresponding (package ...) stanza in
the dune-project file. Since you have at least one other (package ...) stanza
in your dune-project file, you must a (package ...) stanza for each opam
package in your project.
```

**Comment by moyodiallo** [comment]
Thank for the review @reynir .
